ServerName "localhost"
ProxyRequests Off

<VirtualHost *:80>
    ServerName "localhost"
    DocumentRoot "/usr/local/apache2/htdocs"

    <Directory "/usr/local/apache2/htdocs">
        Options None
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
