[yia-default]
user = yia
group = yia
listen = 0.0.0.0:9000
pm = ondemand
pm.max_children = 2
pm.process_idle_timeout = 10s
catch_workers_output = yes
decorate_workers_output = no
clear_env = yes
security.limit_extensions = .php
php_admin_value[xdebug.start_with_request] = no
