from __future__ import annotations

from pathlib import PurePosixPath
from typing import Iterable

from yia.config import ApplicationConfig, NormalizedConfig
from yia.generators import GeneratedFile, GenerationContext

from .php import php_pool_port
from .python import python_service_name


APACHE_VHOSTS_PATH = "apache/vhosts.conf"
APACHE_VHOSTS_CONTAINER_PATH = "/usr/local/apache2/conf/extra/yia-vhosts.conf"
RUNTIME_ROOT = PurePosixPath("/workspace")


def _quote(value: str) -> str:
    if any(character in value for character in ("\x00", "\r", "\n")):
        raise ValueError("Apache values cannot contain control characters")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _application_root(application: ApplicationConfig) -> PurePosixPath:
    return RUNTIME_ROOT / application.name


def _public_directory(application: ApplicationConfig) -> PurePosixPath:
    if application.web is None or application.web.public_directory is None:
        raise ValueError("PHP web application requires a public directory")
    relative = application.web.public_directory.relative_to(application.path)
    if relative == PurePosixPath("."):
        return _application_root(application)
    return _application_root(application).joinpath(*relative.parts)


def _php_vhost(
    config: NormalizedConfig,
    application: ApplicationConfig,
) -> list[str]:
    if application.web is None:
        raise ValueError("HTTP application requires web configuration")
    public_directory = _public_directory(application).as_posix()
    backend = (
        f"proxy:fcgi://{application.runtime.name}:"
        f"{php_pool_port(config, application)}"
    )
    return [
        "<VirtualHost *:80>",
        f"    ServerName {_quote(application.web.hostname)}",
        f"    DocumentRoot {_quote(public_directory)}",
        "    DirectoryIndex index.php index.html",
        "",
        f"    <Directory {_quote(public_directory)}>",
        "        Options FollowSymLinks",
        "        AllowOverride All",
        "        Require all granted",
        "    </Directory>",
        "",
        '    <FilesMatch "\\.php$">',
        f"        SetHandler {_quote(backend)}",
        "    </FilesMatch>",
        "</VirtualHost>",
    ]


def _node_vhost(application: ApplicationConfig) -> list[str]:
    if application.web is None or application.web.port is None:
        raise ValueError("Node web application requires an internal port")
    backend = (
        f"http://{application.runtime.name}-{application.name}:"
        f"{application.web.port}/"
    )
    return [
        "<VirtualHost *:80>",
        f"    ServerName {_quote(application.web.hostname)}",
        "    ProxyPreserveHost On",
        '    RequestHeader set X-Forwarded-Proto "http"',
        f"    ProxyPass {_quote('/')} {_quote(backend)} upgrade=websocket",
        f"    ProxyPassReverse {_quote('/')} {_quote(backend)}",
        "</VirtualHost>",
    ]


def _python_vhost(application: ApplicationConfig) -> list[str]:
    if application.web is None or application.web.port is None:
        raise ValueError("Python web application requires an internal port")
    backend = f"http://{python_service_name(application)}:{application.web.port}/"
    return [
        "<VirtualHost *:80>",
        f"    ServerName {_quote(application.web.hostname)}",
        "    ProxyPreserveHost On",
        '    RequestHeader set X-Forwarded-Proto "http"',
        f"    ProxyPass {_quote('/')} {_quote(backend)}",
        f"    ProxyPassReverse {_quote('/')} {_quote(backend)}",
        "</VirtualHost>",
    ]


def _serialize_vhosts(config: NormalizedConfig) -> str:
    lines = ["# Generated by Yia. Do not edit.", ""]
    for application in config.applications:
        if application.web is None:
            continue
        if application.type == "php":
            lines.extend(_php_vhost(config, application))
        elif application.type == "node":
            lines.extend(_node_vhost(application))
        else:
            lines.extend(_python_vhost(application))
        lines.append("")
    return "\n".join(lines)


class ApacheGenerator:
    name = "apache-vhosts"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedFile]:
        applications = tuple(
            application
            for application in context.config.applications
            if application.web is not None
        )
        if not applications:
            return
        yield GeneratedFile.text(
            APACHE_VHOSTS_PATH,
            _serialize_vhosts(context.config),
        )
