from __future__ import annotations

from collections import defaultdict
from typing import Iterable

from yia.config import ApplicationConfig, NormalizedConfig
from yia.generators import GeneratedFile, GenerationContext


PHP_FPM_BASE_PORT = 9000
PHP_FPM_CONFIG_CONTAINER_PATH = "/usr/local/etc/php-fpm.d/yia-pools.conf"
PHP_BUILD_CONTEXT = "../../.yia/docker/php"
SUPPORTED_PHP_VERSIONS = ("8.2", "8.4", "8.5")


def php_configuration_path(version: str) -> str:
    if version not in SUPPORTED_PHP_VERSIONS:
        raise ValueError(f"unsupported PHP version {version!r}")
    return f"php/{version}/fpm-pools.conf"


def php_applications_by_runtime(
    config: NormalizedConfig,
) -> dict[str, tuple[ApplicationConfig, ...]]:
    grouped: dict[str, list[ApplicationConfig]] = defaultdict(list)
    for application in config.applications:
        if application.type == "php":
            grouped[application.runtime.name].append(application)
    return {
        runtime: tuple(sorted(applications, key=lambda item: item.name))
        for runtime, applications in sorted(grouped.items())
    }


def php_pool_port(
    config: NormalizedConfig,
    application: ApplicationConfig,
) -> int:
    applications = php_applications_by_runtime(config).get(application.runtime.name)
    if applications is None:
        raise ValueError(f"unknown PHP runtime {application.runtime.name!r}")
    for index, candidate in enumerate(applications):
        if candidate.name == application.name:
            return PHP_FPM_BASE_PORT + index
    raise ValueError(f"unknown PHP application {application.name!r}")


def _pool(application: ApplicationConfig, port: int) -> list[str]:
    xdebug_start = "trigger" if application.runtime.xdebug else "no"
    return [
        f"[{application.name}]",
        "user = yia",
        "group = yia",
        f"listen = 0.0.0.0:{port}",
        "pm = dynamic",
        "pm.max_children = 8",
        "pm.start_servers = 2",
        "pm.min_spare_servers = 1",
        "pm.max_spare_servers = 3",
        f"chdir = /workspace/{application.name}",
        "catch_workers_output = yes",
        "decorate_workers_output = no",
        "clear_env = yes",
        "security.limit_extensions = .php",
        "php_admin_flag[log_errors] = on",
        "php_admin_value[error_log] = /proc/self/fd/2",
        f"php_admin_value[xdebug.start_with_request] = {xdebug_start}",
    ]


def _serialize_pools(applications: tuple[ApplicationConfig, ...]) -> str:
    lines = ["; Generated by Yia. Do not edit.", ""]
    for index, application in enumerate(applications):
        lines.extend(_pool(application, PHP_FPM_BASE_PORT + index))
        lines.append("")
    return "\n".join(lines)


class PhpGenerator:
    name = "php-fpm"

    def generate(self, context: GenerationContext) -> Iterable[GeneratedFile]:
        for applications in php_applications_by_runtime(context.config).values():
            version = applications[0].runtime.version
            yield GeneratedFile.text(
                php_configuration_path(version),
                _serialize_pools(applications),
            )
