from pathlib import Path

import yaml

from yia.config import NormalizedConfig, load_normalized_config, normalize_config
from yia.docker import ApacheGenerator, ComposeGenerator, docker_generators
from yia.generators import GenerationContext, GenerationEngine
from yia.state import YiaState


ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "schemas" / "yia.schema.json"


def _fixture_config(name: str) -> NormalizedConfig:
    project_root = ROOT / "tests" / "projects" / name
    return load_normalized_config(project_root / "yia.yml", SCHEMA)


def _apache_files(config: NormalizedConfig):
    context = GenerationContext(config=config, state=YiaState.from_config(config))
    return tuple(ApacheGenerator().generate(context))


def test_apache_is_not_generated_without_http_application() -> None:
    assert _apache_files(_fixture_config("minimal")) == ()
    assert _apache_files(_fixture_config("postgres")) == ()


def test_full_fixture_generates_deterministic_php_and_node_vhosts() -> None:
    config = _fixture_config("full")

    first = _apache_files(config)
    second = _apache_files(config)

    assert first == second
    assert len(first) == 1
    assert first[0].path == "apache/vhosts.conf"
    assert first[0].mode == 0o644
    content = first[0].content.decode("utf-8")
    assert content.startswith("# Generated by Yia. Do not edit.\n")
    assert content.count("<VirtualHost *:80>") == 2
    assert content.index('ServerName "api.full.localhost"') < content.index(
        'ServerName "full.localhost"'
    )

    assert 'DocumentRoot "/workspace/api/public"' in content
    assert '<Directory "/workspace/api/public">' in content
    assert "AllowOverride All" in content
    assert 'SetHandler "proxy:fcgi://php-8.4:9000"' in content

    assert "ProxyPreserveHost On" in content
    assert (
        'ProxyPass "/" "http://node-24-frontend:3000/" '
        "upgrade=websocket"
    ) in content
    assert (
        'ProxyPassReverse "/" "http://node-24-frontend:3000/"' in content
    )
    assert ":443" not in content
    assert "SSLEngine" not in content


def test_php_public_directory_is_mapped_to_the_container_workspace(
    tmp_path: Path,
) -> None:
    (tmp_path / "apps" / "api" / "web root").mkdir(parents=True)
    config = normalize_config(
        {
            "version": 1,
            "project": {"name": "php-web"},
            "environment": {"domain": "php-web.localhost"},
            "applications": {
                "api": {
                    "type": "php",
                    "path": "apps/api",
                    "runtime": {"php": "8.4"},
                    "web": {
                        "hostname": "api.php-web.localhost",
                        "public_directory": "web root",
                    },
                }
            },
        },
        project_root=tmp_path,
    )

    content = _apache_files(config)[0].content.decode("utf-8")

    assert 'DocumentRoot "/workspace/api/web root"' in content
    assert str(tmp_path) not in content


def test_compose_wires_apache_build_healthcheck_and_read_only_mounts() -> None:
    config = _fixture_config("full")
    context = GenerationContext(config=config, state=YiaState.from_config(config))
    compose_file = tuple(ComposeGenerator().generate(context))[0]

    compose = yaml.safe_load(compose_file.content)
    apache = compose["services"]["apache"]

    assert apache["build"] == {
        "context": "../../.yia/docker/apache",
        "dockerfile": "Dockerfile",
    }
    assert apache["healthcheck"]["test"] == [
        "CMD",
        "wget",
        "-q",
        "-O",
        "/dev/null",
        "http://127.0.0.1/.yia-health",
    ]
    assert apache["volumes"][0] == {
        "type": "bind",
        "source": "../apache/vhosts.conf",
        "target": "/usr/local/apache2/conf/extra/yia-vhosts.conf",
        "read_only": True,
    }
    assert apache["volumes"][1]["source"].endswith(
        "/tests/projects/full/apps/api"
    )
    assert apache["volumes"][1]["target"] == "/workspace/api"
    assert apache["volumes"][1]["read_only"] is True


def test_default_docker_generators_are_complete_and_idempotent(
    tmp_path: Path,
) -> None:
    (tmp_path / "apps" / "frontend").mkdir(parents=True)
    config = normalize_config(
        {
            "version": 1,
            "project": {"name": "node-web"},
            "environment": {"domain": "node-web.localhost"},
            "applications": {
                "frontend": {
                    "type": "node",
                    "path": "apps/frontend",
                    "runtime": {"node": "24"},
                    "web": {"hostname": "node-web.localhost", "port": 3000},
                }
            },
        },
        project_root=tmp_path,
    )
    generators = docker_generators()
    engine = GenerationEngine(generators)

    first = engine.generate(config)
    second = engine.generate(config)

    assert tuple(generator.name for generator in generators) == (
        "apache-vhosts",
        "php-fpm",
        "docker-compose",
    )
    assert first.changed is True
    assert second.changed is False
    assert (tmp_path / ".yia-runtime/apache/vhosts.conf").is_file()
    assert (tmp_path / ".yia-runtime/compose/compose.yaml").is_file()
    assert second.manifest.generators == (
        "apache-vhosts",
        "docker-compose",
        "php-fpm",
    )


def test_apache_image_uses_pinned_official_base_and_generated_include() -> None:
    dockerfile = (ROOT / "docker" / "apache" / "Dockerfile").read_text(
        encoding="utf-8"
    )
    health_vhost = (ROOT / "docker" / "apache" / "yia-health.conf").read_text(
        encoding="utf-8"
    )

    assert dockerfile.startswith("FROM httpd:2.4.68-alpine3.24\n")
    for module in ("headers", "proxy", "proxy_fcgi", "proxy_http", "rewrite"):
        assert f"LoadModule {module}_module" in dockerfile
    assert "yia-vhosts.conf" in dockerfile
    assert "ProxyRequests Off" in health_vhost
    assert 'ServerName "localhost"' in health_vhost
    assert "<VirtualHost *:80>" in health_vhost
